<a href="https://colab.research.google.com/github/Narang-Garima/Alzheimer-Prediction-/blob/Projects/missingness.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import seaborn as sns

In [79]:
df = sns.load_dataset('titanic')

In [80]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [81]:
# check missing values
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [82]:
df.shape

(891, 15)

In [41]:
#df.dropna().shape -- this is bad thing as loosing a lot of data

(182, 15)

In [50]:
#df.dropna(axis=1, inplace= True) --- this is for the colm wise deletion-- but here not a right thing to do as age colm will be deleted and we dont want that

## Imputation Techniques-

### 1. Mean Value Imputation

In [83]:
df['Age_mean']= df['age'].fillna(df['age'].mean())

In [84]:
df[['Age_mean','age']]

      Age_mean   age
0    22.000000  22.0
1    38.000000  38.0
2    26.000000  26.0
3    35.000000  35.0
4    35.000000  35.0
..         ...   ...
886  27.000000  27.0
887  19.000000  19.0
888  29.699118   NaN
889  26.000000  26.0
890  32.000000  32.0

[891 rows x 2 columns]

### Mean impuattion works well when we have normally distributed data

### 2. Median Value Imputation- Used when we have outliers in the dataset

In [85]:
df['Age_median']= df['age'].fillna(df['age'].median())

In [86]:
df[['Age_mean','Age_median','age']]

      Age_mean  Age_median   age
0    22.000000        22.0  22.0
1    38.000000        38.0  38.0
2    26.000000        26.0  26.0
3    35.000000        35.0  35.0
4    35.000000        35.0  35.0
..         ...         ...   ...
886  27.000000        27.0  27.0
887  19.000000        19.0  19.0
888  29.699118        28.0   NaN
889  26.000000        26.0  26.0
890  32.000000        32.0  32.0

[891 rows x 3 columns]

### 3. Mode imputation Techniques- for categorical values

In [87]:
df[df['embarked'].isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Age_mean,Age_median
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,38.0,38.0
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,62.0,62.0

In [88]:
df['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [89]:
mode_val =df[df['embarked'].notna()]['embarked'].mode()[0]

In [90]:
df['embarked_mode']=df['embarked'].fillna(mode_val)

In [91]:
df[['embarked_mode','embarked']]

    embarked_mode embarked
0               S        S
1               C        C
2               S        S
3               S        S
4               S        S
..            ...      ...
886             S        S
887             S        S
888             S        S
889             C        C
890             Q        Q

[891 rows x 2 columns]

In [92]:
df['embarked_mode'].isnull().sum()

np.int64(0)

In [93]:
df['embarked'].isnull().sum()

np.int64(2)

### one more method is random sampling imputation- in which select random value n impute null with that